"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv  # type: ignore
import os
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()  # take environment variables from .env file

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    "unfold.contrib.filters",       # Optional but recommended
    "unfold.contrib.forms",         # Optional
    "unfold.contrib.inlines",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # rest framework and JWT
    'rest_framework',
    'rest_framework_simplejwt',

    # cors headers
    'corsheaders',

    # Local apps
    'accounts',
    'shop_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

# CORS_ALLOWED_ORIGINS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.User'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),          # short lived access token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),             # longer refresh token
    'ROTATE_REFRESH_TOKENS': True,                           # issue new refresh on refresh
    'BLACKLIST_AFTER_ROTATION': True,                        # blacklist old refresh token

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',

    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}



UNFOLD = {
    "SITE_TITLE": "Car Parts Stock Manager",
    "SITE_HEADER": "Shop Admin Dashboard",
    "SITE_URL": "/",
    "SITE_SYMBOL": "precision_manufacturing",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "DASHBOARD_CALLBACK": "backend.utils.dashboard.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "#f0f9ff",
            "100": "#e0f2fe",
            "500": "#0ea5e9",
            "600": "#0284c7",
            "900": "#0c4a6e",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Shop & Users"),
                "icon": "storefront",
                "items": [
                    {
                        "title": _("My Shop"),
                        "icon": "store",
                        "link": reverse_lazy("admin:shop_manager_shop_changelist"),
                    },
                    {
                        "title": _("Users & Cashiers"),
                        "icon": "people",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                        "permission": lambda r: r.user.role in ['SuperAdmin', 'ShopAdmin'],
                    },
                    {
                        "title": _("Subscription Plans"),
                        "icon": "subscriptions",
                        "link": reverse_lazy("admin:shop_manager_subscriptionplan_changelist"),
                        "permission": lambda r: r.user.role == 'SuperAdmin',
                    },
                ],
            },
            {
                "title": _("Inventory Management"),
                "icon": "inventory_2",
                "items": [
                    {
                        "title": _("Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:shop_manager_category_changelist"),
                    },
                    {
                        "title": _("Suppliers"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:shop_manager_supplier_changelist"),
                    },
                    {
                        "title": _("Products"),
                        "icon": "precision_manufacturing",
                        "link": reverse_lazy("admin:shop_manager_product_changelist"),
                    },
                    {
                        "title": _("Current Stock"),
                        "icon": "warehouse",
                        "link": reverse_lazy("admin:shop_manager_stock_changelist"),
                    },
                ],
            },
            {
                "title": _("Transactions"),
                "icon": "swap_horiz",
                "items": [
                    {
                        "title": _("Purchases"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:shop_manager_purchase_changelist"),
                    },
                    {
                        "title": _("Sales"),
                        "icon": "point_of_sale",
                        "link": reverse_lazy("admin:shop_manager_sale_changelist"),
                    },
                    {
                        "title": _("Expenses"),
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:shop_manager_expense_changelist"),
                    },
                ],
            },
            {
                "title": _("Reports & Logs"),
                "icon": "analytics",
                "items": [
                    {
                        "title": _("Offline Sync Logs"),
                        "icon": "sync",
                        "link": reverse_lazy("admin:shop_manager_offlinesynclog_changelist"),
                    },
                ],
            },
        ],
    },
}